import './sass/common.scss'
import './sass/css-editor.scss'
import './sass/racePage.scss'
import './sass/winnerDesk.scss'

import './scripts/common'
import './scripts/bodyCreator'
import './scripts/fixHeight'
import './scripts/switchPages'
import './scripts/randomize'
import './scripts/createTrack'
import './scripts/serverRequest'
import './scripts/selectRemoveListener'
import './scripts/updateTrack'
import './scripts/validationName'
import './scripts/removeNodes'
import './scripts/modesShip'
import './scripts/Technical_temporary'
import './scripts/clearUpdateGarage'
import './scripts/localStorage'
import './scripts/restartServer'
import './scripts/switchArenaWinners'
import './scripts/startStopShip'
import './scripts/animation'
import './scripts/raceMode'
import './scripts/winnersTable'
import './scripts/switchWinner'




