import './sass/common.scss'
import './sass/css-editor.scss'
import './sass/racePage.scss'

import './scripts/common'
import './scripts/bodyCreator'
import './scripts/serverRequest'
import './scripts/fixHeight'
import './scripts/switchPages'
import './scripts/randomize'
import './scripts/createTrack'
import './scripts/selectRemoveListener'
import './scripts/updateTrack'
import './scripts/validationName'
import './scripts/removeNodes'
import './scripts/modesSheep'
import './scripts/Techical_temporary'
import './scripts/clearUpdateGarage'


